// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class InvalidloginTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void invalidlogin() {
    // Test name: invalid_login
    // Step # | name | target | value
    // 1 | open | https://twitter.com/ | 
    driver.get("https://twitter.com/");
    // 2 | setWindowSize | 1382x784 | 
    driver.manage().window().setSize(new Dimension(1382, 784));
    // 3 | click | css=.r-13gxpu9 | 
    driver.findElement(By.cssSelector(".r-13gxpu9")).click();
    // 4 | click | name=session[username_or_email] | 
    driver.findElement(By.name("session[username_or_email]")).click();
    // 5 | type | name=session[username_or_email] | alief12345
    driver.findElement(By.name("session[username_or_email]")).sendKeys("alief12345");
    // 6 | click | name=session[password] | 
    driver.findElement(By.name("session[password]")).click();
    // 7 | type | name=session[password] | asaxqxxaxcecwc
    driver.findElement(By.name("session[password]")).sendKeys("asaxqxxaxcecwc");
    // 8 | click | css=.css-1dbjc4n:nth-child(2) > form .css-18t94o4 > .css-901oao | 
    driver.findElement(By.cssSelector(".css-1dbjc4n:nth-child(2) > form .css-18t94o4 > .css-901oao")).click();
  }
}
