// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class PosttextTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void posttext() {
    // Test name: Post_text
    // Step # | name | target | value
    // 1 | open | https://twitter.com/ | 
    driver.get("https://twitter.com/");
    // 2 | setWindowSize | 1382x784 | 
    driver.manage().window().setSize(new Dimension(1382, 784));
    // 3 | click | css=.r-13gxpu9 | 
    driver.findElement(By.cssSelector(".r-13gxpu9")).click();
    // 4 | mouseOver | css=.r-13gxpu9 | 
    {
      WebElement element = driver.findElement(By.cssSelector(".r-13gxpu9"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 5 | type | name=session[username_or_email] | zulava
    driver.findElement(By.name("session[username_or_email]")).sendKeys("zulava");
    // 6 | click | name=session[password] | 
    driver.findElement(By.name("session[password]")).click();
    // 7 | type | name=session[password] | Mahatma35
    driver.findElement(By.name("session[password]")).sendKeys("Mahatma35");
    // 8 | click | css=.css-1dbjc4n:nth-child(2) .css-901oao > .css-901oao > .css-901oao | 
    driver.findElement(By.cssSelector(".css-1dbjc4n:nth-child(2) .css-901oao > .css-901oao > .css-901oao")).click();
    // 9 | mouseOver | css=.css-1dbjc4n:nth-child(3) > .css-4rbku5 > .css-901oao | 
    {
      WebElement element = driver.findElement(By.cssSelector(".css-1dbjc4n:nth-child(3) > .css-4rbku5 > .css-901oao"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 10 | mouseOut | css=.css-1dbjc4n:nth-child(3) > .css-1dbjc4n > .css-1dbjc4n > .css-1dbjc4n > .css-1dbjc4n > .css-1dbjc4n > .css-4rbku5 > .css-901oao | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 11 | click | css=.css-901oao > .css-901oao .css-901oao > .css-901oao | 
    driver.findElement(By.cssSelector(".css-901oao > .css-901oao .css-901oao > .css-901oao")).click();
    // 12 | mouseOver | css=.css-901oao > .css-901oao .css-901oao > .css-901oao | 
    {
      WebElement element = driver.findElement(By.cssSelector(".css-901oao > .css-901oao .css-901oao > .css-901oao"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 13 | mouseOut | css=.css-901oao > .css-901oao .css-901oao > .css-901oao | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 14 | editContent | css=.DraftEditor-editorContainer:nth-child(1) > .notranslate | <div data-contents="true"><div class="" data-block="true" data-editor="daogd" data-offset-key="183s0-0-0"><div data-offset-key="183s0-0-0" class="public-DraftStyleDefault-block public-DraftStyleDefault-ltr"><span data-offset-key="183s0-0-0"><span data-text="true">You need to execute what you think</span></span></div></div></div>
    {
      WebElement element = driver.findElement(By.cssSelector(".DraftEditor-editorContainer:nth-child(1) > .notranslate"));
      js.executeScript("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = '<div data-contents=\"true\"><div class=\"\" data-block=\"true\" data-editor=\"daogd\" data-offset-key=\"183s0-0-0\"><div data-offset-key=\"183s0-0-0\" class=\"public-DraftStyleDefault-block public-DraftStyleDefault-ltr\"><span data-offset-key=\"183s0-0-0\"><span data-text=\"true\">You need to execute what you think</span></span></div></div></div>'}", element);
    }
    // 15 | click | css=.css-18t94o4:nth-child(4) > .css-901oao > .css-901oao > .css-901oao | 
    driver.findElement(By.cssSelector(".css-18t94o4:nth-child(4) > .css-901oao > .css-901oao > .css-901oao")).click();
    // 16 | click | css=.r-1xvli5t:nth-child(1) circle:nth-child(3) | 
    driver.findElement(By.cssSelector(".r-1xvli5t:nth-child(1) circle:nth-child(3)")).click();
    // 17 | click | linkText=Log out @Zulava | 
    driver.findElement(By.linkText("Log out @Zulava")).click();
    // 18 | click | css=.r-jwli3a | 
    driver.findElement(By.cssSelector(".r-jwli3a")).click();
  }
}
